### PR TITLE
Reduce dependencies, ignore drafts, auto set lastModified

### PR DESCRIPTION
**Pull request by eddywashere**
- switched to lodash template
    - fix: I don't use handlebars but I do use lodash. One less dependency by removing it. We all win?
- ignore file.drafts
    - fix: drafts we're being included
- set lastModified to Date.now() if it doesn't exist on the file
    - fix: Some of my automatically generated pages did not have a modified time and were being ignored

### CODE REVIEW

**Comment by boushley** [comment]
@eddywashere This looks good. Thanks for the PR.

**Comment by jseppi** [comment]
Will this be published as a new release soon?

**Comment by boushley** [comment]
I was planning to wait for the other outstanding PR by @eddywashere 

If it doesn't land today though I'll try and remember to publish tonight.

**Comment by jseppi** [comment]
Sweet! :+1:

**Comment by boushley** [comment]
This has been published as part of `0.0.10` to resolve the failing dependency issue.

**Pull request merged**
