### PR TITLE
Fail gracefully

### PR DESCRIPTION
**Pull request by edorsey**
Skips files if they don't have the url frontmatter.

Tries to determine modified from the filesystem if there isn't one specified in the file.

### CODE REVIEW

**Comment by boushley** [comment]
@edorsey These changes look great.

Can I get you to adjust the indentation. It looks like your changes have 2 spaces for indentation, but the rest of the file is 4 spaces.

Thanks again, these are great improvements.

**Comment by edorsey** [comment]
Oops, sorry about that. I've adjusted the indentation.

**Comment by boushley** [comment]
@edorsey Looks good. Landing, thanks for the change!

I wonder if there is anything we can do to help people detect that they have the url property misconfigured. This code would silently skip all of the files if they mistyped their url property configuration. However a warning each time we skip seems like it would be annoying when you have files you want to be skipped. We might be able to do a config option... but that's another enhancement.

Thanks again!

**Comment by boushley** [comment]
@edorsey This should be out as version 0.0.8

**Comment by edorsey** [comment]
Cheers!

**Pull request merged**
